ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_ar.properties Messages_ar.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_cs.properties Messages_cs.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_da.properties Messages_da.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_de.properties Messages_de.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_el.properties Messages_el.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_es.properties Messages_es.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_fi.properties Messages_fi.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_fr.properties Messages_fr.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_hu.properties Messages_hu.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_it.properties Messages_it.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_iw.properties Messages_iw.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_ja.properties Messages_ja.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_ko.properties Messages_ko.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_nl.properties Messages_nl.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_no.properties Messages_no.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_pl.properties Messages_pl.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_pt_BR.properties Messages_pt_BR.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_pt.properties Messages_pt.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_ro.properties Messages_ro.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_ru.properties Messages_ru.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_sk.properties Messages_sk.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_sv.properties Messages_sv.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_th.properties Messages_th.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_tr.properties Messages_tr.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_zh_CN.properties Messages_zh_CN.properties
ade symlink ../../../../../../../../../../../wptg/xdk/src/java/json/resources/oracle/json/parser/Messages_zh_TW.properties Messages_zh_TW.properties

